# Generated by Django 2.0.3 on 2018-08-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=15)),
                ('lugar', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=150)),
                ('fec_inicio', models.DateField()),
                ('fec_fin', models.DateField()),
                ('tipo_evento', models.CharField(max_length=15)),
                ('usuario', models.CharField(max_length=255)),
            ],
        ),
    ]
