# Generated by Django 2.0.3 on 2018-08-15 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20180815_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
