# Generated by Django 2.1 on 2018-09-04 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concursos', '0006_auto_20180904_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='concursos.VideoRelacionado')),
            ],
            options={
                'verbose_name_plural': 'Log Conversión',
                'db_table': 'log_conversion',
                'verbose_name': 'Log Conversión',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('maquina', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Procesos',
                'db_table': 'proceso',
                'verbose_name': 'Proceso',
            },
        ),
    ]
