# Generated by Django 2.1 on 2018-09-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso_conversion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='created_at',
        ),
        migrations.AddField(
            model_name='logconversion',
            name='maquina',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logconversion',
            name='mensaje',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
