# Generated by Django 2.1 on 2018-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso_conversion', '0002_auto_20180905_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logconversion',
            name='video',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
