# Generated by Django 2.1 on 2018-08-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('banner', models.ImageField(null=True, upload_to='static')),
                ('url', models.CharField(max_length=255)),
                ('fec_inicio', models.DateField()),
                ('fec_fin', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'concurso',
                'verbose_name': 'concurso',
                'verbose_name_plural': 'concursos',
            },
        ),
    ]
