# Generated by Django 2.1 on 2018-09-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('banner', models.ImageField(null=True, upload_to='banners/')),
                ('url', models.CharField(max_length=255)),
                ('fec_inicio', models.DateField()),
                ('fec_fin', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'concursos',
                'verbose_name': 'concurso',
                'db_table': 'concurso',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participantes', to='concursos.Concurso')),
            ],
            options={
                'verbose_name_plural': 'participantes',
                'verbose_name': 'participante',
                'db_table': 'participante',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='concursos.Participante')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRelacionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('video_convertido', models.FileField(blank=True, default=None, null=True, upload_to='videos/convertidos/')),
                ('estado', models.CharField(choices=[('Por Hacer', 'TODO'), ('En progreso', 'DOING'), ('Procesado', 'DONE'), ('Error al procesar', 'ERROR')], default='Por Hacer', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'videos relacionados',
                'verbose_name': 'video relacionado',
                'db_table': 'video_relacionado',
            },
        ),
        migrations.AddField(
            model_name='participantevideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='concursos.VideoRelacionado'),
        ),
    ]
