# Generated by Django 2.1 on 2018-09-06 08:11

import concursos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorelacionado',
            name='concurso',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='concursos.Concurso'),
        ),
        migrations.AddField(
            model_name='videorelacionado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='videorelacionado',
            name='video',
            field=models.FileField(upload_to=concursos.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='videorelacionado',
            name='video_convertido',
            field=models.FileField(blank=True, default=None, null=True, upload_to=concursos.models.get_file_converted_path),
        ),
    ]
