# Generated by Django 2.1 on 2018-08-26 17:13

import concursos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'participante',
                'verbose_name_plural': 'participantes',
                'db_table': 'participante',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='concursos.Participante')),
            ],
        ),
        migrations.CreateModel(
            name='VideoRelacionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('estado', models.CharField(choices=[(concursos.models.EstadosVideoOpciones('Por Hacer'), 'Por Hacer'), (concursos.models.EstadosVideoOpciones('En progreso'), 'En progreso'), (concursos.models.EstadosVideoOpciones('Procesado'), 'Procesado'), (concursos.models.EstadosVideoOpciones('Error al procesar'), 'Error al procesar')], default=concursos.models.EstadosVideoOpciones('Por Hacer'), max_length=10)),
            ],
            options={
                'verbose_name': 'video relacionado',
                'verbose_name_plural': 'videos relacionados',
                'db_table': 'video_relacionado',
            },
        ),
        migrations.AlterField(
            model_name='concurso',
            name='banner',
            field=models.ImageField(null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='participantevideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='concursos.VideoRelacionado'),
        ),
        migrations.AddField(
            model_name='participante',
            name='concurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='concursos.Concurso'),
        ),
    ]
