# Generated by Django 2.1 on 2018-09-02 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0002_auto_20180826_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='concurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participantes', to='concursos.Concurso'),
        ),
    ]
