# Generated by Django 2.1 on 2018-09-06 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0003_auto_20180906_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantevideo',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concursos.Participante'),
        ),
        migrations.AlterField(
            model_name='participantevideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concursos.VideoRelacionado'),
        ),
    ]
