# Generated by Django 2.1 on 2018-09-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0004_auto_20180902_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='banner',
            field=models.ImageField(null=True, upload_to='banners/'),
        ),
    ]
