# Generated by Django 2.1.2 on 2018-10-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0004_auto_20180906_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurso',
            name='banner',
            field=models.FileField(null=True, upload_to='banners/'),
        ),
    ]
