# Generated by Django 2.1 on 2018-09-06 02:46

import concursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0005_auto_20180902_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorelacionado',
            name='estado',
            field=models.CharField(choices=[('TODO', 'Por Hacer'), ('DOING', 'En progreso'), ('DONE', 'Procesado'), ('ERROR', 'Error al procesar')], default='TODO', max_length=10),
        ),
        migrations.AlterField(
            model_name='videorelacionado',
            name='video',
            field=models.FileField(upload_to=concursos.models.get_file_path),
        ),
    ]
