# Generated by Django 2.1 on 2018-09-04 23:15

import concursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0005_auto_20180902_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorelacionado',
            name='video_convertido',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videorelacionado',
            name='estado',
            field=models.CharField(choices=[('TODO', 'Por Hacer'), ('DOING', 'En progreso'), ('DONE', 'Procesado'), ('ERROR', 'Error al procesar')], default=concursos.models.EstadosVideoOpciones('Por Hacer'), max_length=10),
        ),
    ]
