# Generated by Django 2.1 on 2018-09-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0006_auto_20180904_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorelacionado',
            name='video_convertido',
            field=models.FileField(blank=True, default=None, null=True, upload_to='videos/convertidos/'),
        ),
    ]
