# Generated by Django 2.1 on 2018-09-06 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0006_auto_20180905_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorelacionado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
