# Generated by Django 2.1 on 2018-09-06 03:39

import concursos.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0006_auto_20180904_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='videorelacionado',
            name='concurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='concursos.Concurso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videorelacionado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videorelacionado',
            name='estado',
            field=models.CharField(choices=[('Por Hacer', 'TODO'), ('En progreso', 'DOING'), ('Procesado', 'DONE'), ('Error al procesar', 'ERROR')], default='Por Hacer', max_length=100),
        ),
        migrations.AlterField(
            model_name='videorelacionado',
            name='video',
            field=models.FileField(upload_to=concursos.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='videorelacionado',
            name='video_convertido',
            field=models.FileField(blank=True, default=None, null=True, upload_to=concursos.models.get_file_converted_path),
        ),
    ]
