# Generated by Django 2.1 on 2018-09-05 02:27

import concursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0007_auto_20180904_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorelacionado',
            name='estado',
            field=models.CharField(choices=[('Por Hacer', 'TODO'), ('En progreso', 'DOING'), ('Procesado', 'DONE'), ('Error al procesar', 'ERROR')], default=concursos.models.EstadosVideoOpciones('Por Hacer'), max_length=10),
        ),
    ]
