# Generated by Django 2.1 on 2018-09-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0009_auto_20180904_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videorelacionado',
            name='estado',
            field=models.CharField(choices=[('Por Hacer', 'TODO'), ('En progreso', 'DOING'), ('Procesado', 'DONE'), ('Error al procesar', 'ERROR')], default='Por Hacer', max_length=100),
        ),
    ]
